"""Catalog and readiness checks for free/local model paths.

The catalog is deliberately advisory: it never downloads large model weights or
starts a local server without an explicit user action. Status is derived from the
same tool registry used by the production selectors.
"""

from __future__ import annotations

from typing import Any


FREE_MODEL_DEFINITIONS: tuple[dict[str, Any], ...] = (
    {
        "id": "local-image-diffusers",
        "name": "Stable Diffusion / Diffusers",
        "category": "Ảnh",
        "tool": "local_diffusion",
        "runtime": "local_gpu",
        "model": "stabilityai/stable-diffusion-2-1-base",
        "cost": "0 USD / lượt",
        "requirements": "diffusers + PyTorch; GPU khuyến nghị, CPU vẫn chạy được nhưng chậm",
        "setup": "pip install diffusers transformers accelerate torch",
        "env": ["LOCAL_IMAGE_MODEL"],
    },
    {
        "id": "comfyui-image",
        "name": "ComfyUI — Flux 2 / workflow ảnh",
        "category": "Ảnh",
        "tool": "comfyui_image",
        "runtime": "local_gpu",
        "model": "Flux 2 hoặc workflow tự chọn",
        "cost": "0 USD / lượt",
        "requirements": "ComfyUI đang chạy và model weights đã tải",
        "setup": "Cài ComfyUI, chạy tại http://localhost:8188",
        "env": ["COMFYUI_SERVER_URL", "COMFYUI_IMAGE_SERVER_URL"],
    },
    {
        "id": "local-video-wan",
        "name": "WAN / Hunyuan / CogVideo local",
        "category": "Video",
        "tool": "wan_video",
        "runtime": "local_gpu",
        "model": "WAN 2.1/2.2, HunyuanVideo, CogVideoX",
        "cost": "0 USD / lượt",
        "requirements": "diffusers + PyTorch; NVIDIA GPU hoặc Apple Silicon MPS",
        "setup": "Bật VIDEO_GEN_LOCAL_ENABLED và chọn VIDEO_GEN_LOCAL_MODEL",
        "env": ["VIDEO_GEN_LOCAL_ENABLED", "VIDEO_GEN_LOCAL_MODEL"],
    },
    {
        "id": "local-video-ltx",
        "name": "LTX-2 local",
        "category": "Video",
        "tool": "ltx_video_local",
        "runtime": "local_gpu",
        "model": "Lightricks/LTX-2",
        "cost": "0 USD / lượt",
        "requirements": "diffusers + PyTorch; GPU khuyến nghị",
        "setup": "Bật VIDEO_GEN_LOCAL_ENABLED=true và chọn ltx2-local",
        "env": ["VIDEO_GEN_LOCAL_ENABLED", "VIDEO_GEN_LOCAL_MODEL"],
    },
    {
        "id": "comfyui-video",
        "name": "ComfyUI — WAN video / workflow video",
        "category": "Video",
        "tool": "comfyui_video",
        "runtime": "local_gpu",
        "model": "WAN 2.2 hoặc workflow tự chọn",
        "cost": "0 USD / lượt",
        "requirements": "ComfyUI đang chạy và model weights đã tải",
        "setup": "Cài ComfyUI, chạy tại http://localhost:8188",
        "env": ["COMFYUI_SERVER_URL", "COMFYUI_VIDEO_SERVER_URL"],
    },
    {
        "id": "piper-tts",
        "name": "Piper TTS local",
        "category": "Giọng nói",
        "tool": "piper_tts",
        "runtime": "local",
        "model": "en_US-lessac-medium hoặc voice model tương thích",
        "cost": "0 USD / lượt",
        "requirements": "piper binary và voice model",
        "setup": "pip install piper-tts rồi tải voice model",
        "env": ["PIPER_MODEL"],
    },
    {
        "id": "whisper-local",
        "name": "faster-whisper local",
        "category": "Phân tích âm thanh",
        "tool": "transcriber",
        "runtime": "local",
        "model": "tiny / base / small / medium / large-v3",
        "cost": "0 USD / lượt",
        "requirements": "faster-whisper; CPU được, GPU giúp nhanh hơn",
        "setup": "pip install faster-whisper",
        "env": ["WHISPER_MODEL_SIZE"],
    },
    {
        "id": "comfyui-music",
        "name": "ACE-Step local qua ComfyUI",
        "category": "Âm nhạc",
        "tool": "comfyui_music",
        "runtime": "local_gpu",
        "model": "ACE-Step 1 / 3.5B",
        "cost": "0 USD / lượt",
        "requirements": "ComfyUI và ACE-Step checkpoint",
        "setup": "Cài ComfyUI, tải ACE-Step checkpoint, chạy local server",
        "env": ["COMFYUI_SERVER_URL", "COMFYUI_MUSIC_SERVER_URL"],
    },
    {
        "id": "vieneu-tts",
        "name": "VieNeu-TTS v3 Turbo",
        "category": "Giọng nói",
        "tool": "vieneu_tts",
        "runtime": "local",
        "model": "Tiếng Việt 3 miền · 23 giọng · voice cloning",
        "cost": "0 USD / lượt",
        "requirements": "CPU/ONNX trên Windows và macOS; GPU NVIDIA tùy chọn",
        "setup": "Model Center cài runtime riêng và model INT8",
        "env": ["VIENEU_MODEL_DIR"],
    },
    {
        "id": "kokoro-tts",
        "name": "Kokoro 82M",
        "category": "Giọng nói",
        "tool": "kokoro_tts",
        "runtime": "local",
        "model": "TTS tiếng Anh nhẹ, 4 voice pack mặc định",
        "cost": "0 USD / lượt",
        "requirements": "CPU được; GPU giúp nhanh hơn",
        "setup": "Model Center cài Kokoro runtime và voice pack",
        "env": ["KOKORO_MODEL_DIR"],
    },
    {
        "id": "realesrgan",
        "name": "Real-ESRGAN x2/x4",
        "category": "Hậu kỳ",
        "tool": "upscale",
        "runtime": "local_gpu",
        "model": "Ảnh/video thường và anime",
        "cost": "0 USD / lượt",
        "requirements": "PyTorch; CUDA/MPS hoặc CPU fallback",
        "setup": "Model Center cài checkpoint và runtime riêng",
        "env": ["REALESRGAN_MODEL_DIR"],
    },
    {
        "id": "rembg-u2net",
        "name": "rembg — U2Net / Silueta",
        "category": "Hậu kỳ",
        "tool": "bg_remove",
        "runtime": "local",
        "model": "Xóa nền, alpha matte, xử lý batch",
        "cost": "0 USD / lượt",
        "requirements": "ONNX Runtime; chạy CPU trên máy phổ thông",
        "setup": "Model Center cài U2Net, Silueta và rembg",
        "env": ["U2NET_HOME"],
    },
    {
        "id": "face-restore",
        "name": "GFPGAN / CodeFormer",
        "category": "Nghiên cứu",
        "tool": "face_restore",
        "runtime": "local_gpu",
        "model": "Phục hồi khuôn mặt và giảm artifact",
        "cost": "0 USD / lượt",
        "requirements": "8 GB RAM; CodeFormer có license phi thương mại",
        "setup": "Chỉ tải sau khi xác nhận license",
        "env": ["FACE_RESTORE_MODEL_DIR"],
    },
    {
        "id": "rife-interpolation",
        "name": "RIFE Frame Interpolation",
        "category": "Hậu kỳ video",
        "tool": "frame_interpolate",
        "runtime": "local_gpu",
        "model": "Tăng FPS và slow motion bằng NCNN/Vulkan",
        "cost": "0 USD / lượt",
        "requirements": "Windows/macOS có Vulkan/Metal tương thích",
        "setup": "Model Center tải binary + model theo hệ điều hành",
        "env": ["RIFE_MODEL_DIR"],
    },
    {
        "id": "florence-vision",
        "name": "Florence-2 Base",
        "category": "Phân tích hình ảnh",
        "tool": "florence_vision",
        "runtime": "local_gpu",
        "model": "Caption, object detection, segmentation, shot analysis",
        "cost": "0 USD / lượt",
        "requirements": "8 GB RAM; CUDA/MPS hoặc CPU",
        "setup": "Model Center cài Transformers runtime riêng",
        "env": ["FLORENCE_MODEL_DIR"],
    },
    {
        "id": "paddleocr",
        "name": "PaddleOCR v5 Mobile",
        "category": "OCR",
        "tool": "paddle_ocr",
        "runtime": "local",
        "model": "Nhận diện chữ Latin và tiếng Việt trong ảnh/video",
        "cost": "0 USD / lượt",
        "requirements": "CPU được; model mobile nhẹ",
        "setup": "Model Center cài detector, recognizer và Paddle runtime",
        "env": ["PADDLEOCR_MODEL_DIR"],
    },
    {
        "id": "depth-anything",
        "name": "Depth Anything V2 Small",
        "category": "Chiều sâu",
        "tool": "depth_estimator",
        "runtime": "local_gpu",
        "model": "Depth map cho parallax, 2.5D và camera giả",
        "cost": "0 USD / lượt",
        "requirements": "8 GB RAM; chỉ bản Small dùng Apache-2.0",
        "setup": "Model Center cài model Small và Transformers runtime",
        "env": ["DEPTH_ANYTHING_MODEL_DIR"],
    },
    {
        "id": "sam2-segmentation",
        "name": "SAM 2.1 Hiera Tiny",
        "category": "Phân đoạn video",
        "tool": "sam2_segment",
        "runtime": "local_gpu",
        "model": "Tách và theo dõi vật thể xuyên suốt video",
        "cost": "0 USD / lượt",
        "requirements": "8 GB RAM; CUDA tốt nhất, CPU/MPS có thể chậm",
        "setup": "Model Center cài SAM2 Tiny và PyTorch runtime",
        "env": ["SAM2_MODEL_DIR"],
    },
    {
        "id": "musetalk-lipsync",
        "name": "MuseTalk 1.5",
        "category": "Lip-sync",
        "tool": "musetalk_lipsync",
        "runtime": "local_gpu",
        "model": "Đồng bộ khẩu hình cho talking-head",
        "cost": "0 USD / lượt",
        "requirements": "16 GB RAM; NVIDIA GPU khuyến nghị",
        "setup": "Model Center cài toàn bộ checkpoint phụ thuộc",
        "env": ["MUSETALK_MODEL_DIR"],
    },
    {
        "id": "wav2lip-research",
        "name": "Wav2Lip GAN",
        "category": "Nghiên cứu",
        "tool": "lip_sync",
        "runtime": "local_gpu",
        "model": "Lip-sync cũ; nghiêm cấm dùng thương mại",
        "cost": "0 USD / lượt",
        "requirements": "8 GB RAM; personal/research/non-commercial only",
        "setup": "Chỉ tải sau khi xác nhận license",
        "env": ["WAV2LIP_PATH"],
    },
    {
        "id": "mlx-whisper",
        "name": "MLX Whisper Base",
        "category": "Phân tích âm thanh",
        "tool": "mlx_transcriber",
        "runtime": "local",
        "model": "Whisper tối ưu riêng cho Apple Silicon",
        "cost": "0 USD / lượt",
        "requirements": "Chỉ macOS Apple Silicon",
        "setup": "Model Center cài MLX runtime và weights",
        "env": ["MLX_WHISPER_MODEL_DIR"],
    },
    {
        "id": "musicgen-research",
        "name": "MusicGen Small",
        "category": "Nghiên cứu",
        "tool": "musicgen_local",
        "runtime": "local_gpu",
        "model": "Text-to-music; không dùng mặc định cho thương mại",
        "cost": "0 USD / lượt",
        "requirements": "12 GB RAM; weights CC-BY-NC-4.0",
        "setup": "Chỉ tải sau khi xác nhận research license",
        "env": ["MUSICGEN_MODEL_DIR"],
    },
    {
        "id": "qwen-vl-research",
        "name": "Qwen2.5-VL 3B",
        "category": "Nghiên cứu",
        "tool": "qwen_vl_local",
        "runtime": "local_gpu",
        "model": "Vision-language; research license",
        "cost": "0 USD / lượt",
        "requirements": "16 GB RAM; tải hơn 7 GB weights",
        "setup": "Chỉ tải sau khi xác nhận Qwen Research License",
        "env": ["QWEN_VL_MODEL_DIR"],
    },
)


def free_model_catalog() -> list[dict[str, Any]]:
    """Return model definitions enriched with live registry readiness."""
    from backlot.model_installer import install_catalog
    from tools.tool_registry import registry

    installs = {item["id"]: item for item in install_catalog()}
    registry.ensure_discovered()
    tools = {name: registry.get(name) for name in registry.list_all()}
    catalog: list[dict[str, Any]] = []
    for definition in FREE_MODEL_DEFINITIONS:
        item = dict(definition)
        tool = tools.get(item["tool"])
        if tool is None:
            item.update({"available": False, "status": "missing", "status_label": "Chưa có tool"})
        else:
            try:
                status = tool.get_status().value
            except Exception:
                status = "unavailable"
            item.update({
                "available": status == "available",
                "status": status,
                "status_label": "SẴN SÀNG" if status == "available" else "CHƯA SẴN SÀNG",
                "tool_version": getattr(tool, "version", None),
            })
        item["installer"] = installs.get(item["id"])
        catalog.append(item)
    return catalog
